a:
  - data: 1
    result: true
  - data: 2
    result: true
  - data: 3
    result: true
b:
  - data: 1
    result: true
  - data: 2
    result: true
  - data: "three"
    result: false
s:
  - one
  - two
  - three
